rm: backend tests from workflow

diff --git a/.github/workflows/Tables_Booking_Workflow.yml b/.github/workflows/Tables_Booking_Workflow.yml
--- a/.github/workflows/Tables_Booking_Workflow.yml
+++ b/.github/workflows/Tables_Booking_Workflow.yml
@@ -22,51 +22,50 @@ jobs:
             - Сообщение: ${{ github.event.head_commit.message }}
             - Ссылка: ${{ github.server_url }}/${{ github.repository }}/commit/${{github.sha}}
 
-# Запуск тестов бэкэнда
-  backend_tests:
-    runs-on: ubuntu-latest
-    steps: 
-      - uses: actions/checkout@v5
-      - name: Set-up python
-        uses: actions/setup-python@v6
-        with: 
-          python-version: 3.11
-      - name: Install dependencies
-        run: |
-          python -m pip install --upgrade pip
-          pip install -r ./src/requirements.txt
-      - name: run pytest
-        env:
-          DB_HOST: localhost
-          DB_PORT: 5432
-          DB_NAME: test
-          DB_USER: test
-          DB_PASSWORD: test
-          SECRET: test_secret
-          JWT_ALGORITHM: HS256
-          ACCESS_TOKEN_EXPIRE_MINUTES: 1
-          DB_RETRY_MAX_ATTEMPTS: 3
-          DB_RETRY_DELAY_SECONDS: 0.1
+# # Запуск тестов бэкэнда
+#   backend_tests:
+#     runs-on: ubuntu-latest
+#     steps: 
+#       - uses: actions/checkout@v5
+#       - name: Set-up python
+#         uses: actions/setup-python@v6
+#         with: 
+#           python-version: 3.11
+#       - name: Install dependencies
+#         run: |
+#           python -m pip install --upgrade pip
+#           pip install -r ./src/requirements.txt
+#       - name: run pytest
+#         env:
+#           DB_USER: fastapi_user
+#           DB_PASSWORD: supersecretpassword
+#           DB_NAME: fastapi_db
+#           DB_HOST: db
+#           DB_PORT: 5432
+#           DB_ENGINE: postgres
+#           SECRET: test_secret
+#           JWT_ALGORITHM: HS256
+#           ACCESS_TOKEN_EXPIRE_MINUTES: 1
+#           DB_RETRY_MAX_ATTEMPTS: 3
+#           DB_RETRY_DELAY_SECONDS: 0.1
           
-        run: python -m pytest tests/ -v -m "not skip" 
+#         run: python -m pytest tests/ -v -m "not skip" 
 
-      - name: Send message
-        if: success() || failure()
-        uses: appleboy/telegram-action@master
-        with:
-          to: ${{ secrets.TELEGRAM_KOM_AE }}
-          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
-          message: |
-            Статус выполнения задачи Action:
-            - Задача: ${{ github.job }}
-            - Статус: ${{ job.status }}
+#       - name: Send message
+#         if: success() || failure()
+#         uses: appleboy/telegram-action@master
+#         with:
+#           to: ${{ secrets.TELEGRAM_KOM_AE }}
+#           token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
+#           message: |
+#             Статус выполнения задачи Action:
+#             - Задача: ${{ github.job }}
+#             - Статус: ${{ job.status }}
 
 # Собрать образ бэкэнда и залить на DockerHub
   build_backend_and_push_to_docker_hub:
     name: Push Docker image to DockerHub
     runs-on: ubuntu-latest
-    needs: 
-      - backend_tests
     steps:
       - name: Check out the repo
         uses: actions/checkout@v5
